name = "Antarchy Craft"
author = "JAB-dev"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e948c7eed2529baf59cb3334ca6652ffe9da7c39feb7230e2b16f1d392793ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
