name = "Antarchy Craft"
author = "JAB-dev"
version = "1.0.43"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aebc0416c6661efe5223e5286a38f57109ec9648035e274d7098f5be4b4f5f5a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
