name = "Antarchy Craft"
author = "JAB-dev"
version = "1.0.43"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64a943ff3ac447849163a7d30f99bc2f13951dc6ea50f2e19f6a22abbfff11d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
