# Antarchy Craft default server.properties
view-distance=8
simulation-distance=6
max-players=20
network-compression-threshold=256
sync-chunk-writes=false
online-mode=true
spawn-protection=0
max-tick-time=60000
